VERSION_TAG=$(shell date +'%y.%m.%d')
PWD=$(shell pwd)
GEN=build/gen
TYPST_FONTS=typst/fonts

.PHONY: build bash gen resume detailed typst typst-resume typst-detailed md site clean distclean all

build:
	docker build -f build/Dockerfile -t tex:latest -t tex:$(VERSION_TAG) .

bash:
	docker run --rm -it -v $(PWD):/data tex:latest bash

# Generate all source files (typst + tex + md, both variants) and the html site.
gen:
	go run ./cmd/resume all --input resume.yaml
	mkdir -p $(GEN)/assets
	cp pictures/61673.jpg $(GEN)/assets/profile.jpg

# LaTeX PDFs (compiled with LuaLaTeX in Docker) from generated .tex.
resume: gen
	mkdir -p dist
	docker run --rm -v $(PWD):/data tex:latest lualatex -interaction=nonstopmode -output-directory dist $(GEN)/resume.tex
	mv dist/resume.pdf dist/George_Messiha_Resume.pdf

detailed: gen
	mkdir -p dist
	docker run --rm -v $(PWD):/data tex:latest lualatex -interaction=nonstopmode -output-directory dist $(GEN)/resume_detailed.tex
	mv dist/resume_detailed.pdf dist/George_Messiha_detailed_resume.pdf

# Typst PDFs from generated .typ.
typst-resume: gen
	mkdir -p dist
	typst compile --font-path $(TYPST_FONTS) $(GEN)/resume.typ dist/George_Messiha_Resume_v2.pdf

typst-detailed: gen
	mkdir -p dist
	typst compile --font-path $(TYPST_FONTS) $(GEN)/resume_detailed.typ dist/George_Messiha_detailed_resume_v2.pdf

typst: typst-resume typst-detailed

# Markdown resumes (generated by `gen`); copy to dist with public names.
md: gen
	mkdir -p dist
	cp $(GEN)/resume.md dist/George_Messiha_Resume.md
	cp $(GEN)/resume_detailed.md dist/George_Messiha_detailed_resume.md

# HTML mini-site (summary variant) for GitHub Pages.
site: gen

clean:
	rm -f dist/*.aux dist/*.out dist/*.log

# Remove all generated output (PDFs, Markdown, sources, site).
distclean:
	rm -rf dist $(GEN) site

all: build resume detailed typst md site clean
